version: "2"

linters:
  disable-all: true
  enable:
    - govet

linters-settings:
  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - composites
      - copylocks
      - nilfunc
      - printf
      - stdmethods
      - structtag

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - govet
    - path: testing/mocks/
      linters:
        - govet
    - path: performance/
      linters:
        - govet
    - path: observability/
      linters:
        - govet
    - path: distributed/
      linters:
        - govet
  max-issues-per-linter: 0
  max-same-issues: 0
