version: "2"

linters:
  # Use 'none' to disable all by default, then enable only what we need
  default: none

  enable:
    - govet

  settings:
    govet:
      enable:
        - atomic
        - bools
        - composites
        - copylocks
        - nilfunc
        - printf
        - stdmethods
        - structtag

  # Exclusion rules for test files and specific paths
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - govet
      - path: testing/mocks/
        linters:
          - govet
      - path: performance/
        linters:
          - govet
      - path: observability/
        linters:
          - govet
      - path: distributed/
        linters:
          - govet

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
